<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Menhir</string>
    <key>fileTypes</key>
    <array>
      <string>mly</string>
    </array>
    <key>scopeName</key>
    <string>source.menhir</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?=%[^%])</string>
        <key>end</key>
        <string>(?=%%)</string>
        <key>patterns</key>
      </dict>
    </array>
  </dict>
</plist>